### ISSUE TITLE
Issue with MakeMasterSky on standard star if wavelength channel is specified

### ISSUE THREAD

**Issue by rremigio** [Keck-DataReductionPipelines/KCWI_DRP#147] opened 2023-09-16 07:23 UTC
Hello,

I have recently re-run the `kcrm_merge` branch (defe9d7fdc154e07dcf85a63ce153b8627f22954) of the DRP on commissioning data of a standard star (bd26d2606) and found that the DRP fails and returns the following error message, which points at an array size mismatch:

![Screenshot from 2023-09-15 19-41-29](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/assets/42788999/0afee491-1859-485b-b98b-d529aa2ce8aa)

I have tried earlier versions of this branch, and I think this may be linked to when the channel is specified when running the `reduce_kcwi` script. If I run an earlier commit (88100e4aee513e01ed2203af131ff5b17e2ddaca) without specifying the wavelength channel, i.e.  `reduce_kcwi -l calib.lst`, I am able to get a datacube of the standard star just fine. However, if I do specify the wavelength channel, i.e `reduce_kcwi -r -l calib.lst`, the DRP stops and returns the same error above.

**Comment by scizen9** [comment] 2023-09-16 15:32
Can you please include the date and the image number of the image that failed.  We can try to reproduce the error.  That is the best way to debug this.

**Comment by rremigio** [comment] 2023-09-16 18:35
The data is from the June 20th commissioning run, and it is frame 149. That is, the file in question is `kr230620_00149.fits`.

**Comment by scizen9** [comment] 2023-10-04 21:54
I have successfully reduced that standard star without encountering the error you report.  However, the pipeline has undergone several changes since you first filed this issue and it is entirely possible the issue was discovered independently and fixed in the process of development.

I did however note:

1. I had to use -t 0.1 on the command line to get a good wavelength solution: there are very few lines.
2. The standard itself was close to the edge of the slice in that frame.

I fear you have just been the victim of working with a branch in development.  I think if you pull the latest version and start from the raw files (and add the -t 0.1 to your command line), you will get a reasonable result.

**Closed by scizen9** 2023-10-04 21:54 UTC
